alias cd-='cd -'
alias cd..='cd ..'
alias du='du -ahx --max-depth=1'
alias ll='ls -lAh'
alias nano='nano -AELOSwim -T 4'
alias ps='ps -o pid,user,args'
alias tarbz2='tar -xjvf'
alias targz='tar -xzvf'
alias tarxz='tar -xJvf'
alias timestamp="date '+%s'"
alias tree='tree -CA'
